[package]
name = "lean-override"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Single C-ABI surface. Re-exports overrideable lean_xxx symbols backed by Rust impls in per-subsystem crates."
publish = false

[dependencies]
lean-runtime-sys.workspace = true
lean-meta.workspace = true
lean-parser.workspace = true

[lib]
crate-type = ["staticlib", "rlib"]
